{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.13","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"gpu","dataSources":[{"sourceId":2002504,"sourceType":"datasetVersion","datasetId":1198025},{"sourceId":8250154,"sourceType":"datasetVersion","datasetId":4895093},{"sourceId":8250300,"sourceType":"datasetVersion","datasetId":4895203},{"sourceId":8252175,"sourceType":"datasetVersion","datasetId":4896605},{"sourceId":8252435,"sourceType":"datasetVersion","datasetId":4896795},{"sourceId":8252725,"sourceType":"datasetVersion","datasetId":4897010}],"dockerImageVersionId":30699,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":true}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"!git clone https://github.com/isl-org/ZoeDepth.git","metadata":{"_uuid":"927429b8-e5c7-4ade-b07a-f9028bdcb700","_cell_guid":"be980acd-8767-4d19-a912-168ba103a575","collapsed":false,"jupyter":{"outputs_hidden":false},"execution":{"iopub.status.busy":"2024-05-02T05:35:16.666994Z","iopub.execute_input":"2024-05-02T05:35:16.667381Z","iopub.status.idle":"2024-05-02T05:35:18.740997Z","shell.execute_reply.started":"2024-05-02T05:35:16.667350Z","shell.execute_reply":"2024-05-02T05:35:18.739786Z"},"trusted":true},"execution_count":1,"outputs":[{"name":"stdout","text":"Cloning into 'ZoeDepth'...\nremote: Enumerating objects: 111, done.\u001b[K\nremote: Counting objects: 100% (105/105), done.\u001b[K\nremote: Compressing objects: 100% (77/77), done.\u001b[K\nremote: Total 111 (delta 39), reused 63 (delta 24), pack-reused 6\u001b[K\nReceiving objects: 100% (111/111), 4.09 MiB | 20.05 MiB/s, done.\nResolving deltas: 100% (39/39), done.\n","output_type":"stream"}]},{"cell_type":"code","source":"cd /kaggle/working/","metadata":{"_uuid":"6c2f4728-3f4e-419a-9d65-7d964ae724cc","_cell_guid":"0e942529-d9ff-4e63-acc2-04a8d550223a","collapsed":false,"jupyter":{"outputs_hidden":false},"execution":{"iopub.status.busy":"2024-04-28T12:34:03.567744Z","iopub.execute_input":"2024-04-28T12:34:03.568114Z","iopub.status.idle":"2024-04-28T12:34:03.575044Z","shell.execute_reply.started":"2024-04-28T12:34:03.568082Z","shell.execute_reply":"2024-04-28T12:34:03.574097Z"},"trusted":true},"execution_count":2,"outputs":[{"name":"stdout","text":"/kaggle/working\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install timm==0.6.7","metadata":{"_uuid":"0904284d-dead-448f-a98d-de2f27d7f8ae","_cell_guid":"e51ef678-6323-4dbf-a775-523039106136","collapsed":false,"jupyter":{"outputs_hidden":false},"execution":{"iopub.status.busy":"2024-05-02T05:35:22.679085Z","iopub.execute_input":"2024-05-02T05:35:22.679817Z","iopub.status.idle":"2024-05-02T05:35:37.879763Z","shell.execute_reply.started":"2024-05-02T05:35:22.679778Z","shell.execute_reply":"2024-05-02T05:35:37.878626Z"},"trusted":true},"execution_count":2,"outputs":[{"name":"stdout","text":"Collecting timm==0.6.7\n  Downloading timm-0.6.7-py3-none-any.whl.metadata (33 kB)\nRequirement already satisfied: torch>=1.4 in /opt/conda/lib/python3.10/site-packages (from timm==0.6.7) (2.1.2)\nRequirement already satisfied: torchvision in /opt/conda/lib/python3.10/site-packages (from timm==0.6.7) (0.16.2)\nRequirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (3.13.1)\nRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (4.9.0)\nRequirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (1.12)\nRequirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (3.2.1)\nRequirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (3.1.2)\nRequirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch>=1.4->timm==0.6.7) (2024.2.0)\nRequirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from torchvision->timm==0.6.7) (1.26.4)\nRequirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from torchvision->timm==0.6.7) (2.31.0)\nRequirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.10/site-packages (from torchvision->timm==0.6.7) (9.5.0)\nRequirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.4->timm==0.6.7) (2.1.3)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->timm==0.6.7) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->timm==0.6.7) (3.6)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->timm==0.6.7) (1.26.18)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->timm==0.6.7) (2024.2.2)\nRequirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.4->timm==0.6.7) (1.3.0)\nDownloading timm-0.6.7-py3-none-any.whl (509 kB)\n\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m510.0/510.0 kB\u001b[0m \u001b[31m24.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hInstalling collected packages: timm\n  Attempting uninstall: timm\n    Found existing installation: timm 0.9.16\n    Uninstalling timm-0.9.16:\n      Successfully uninstalled timm-0.9.16\nSuccessfully installed timm-0.6.7\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install wandb==0.13.9\n!pip install scipy==1.10.0\n!pip install torchaudio==0.13.1\n!pip install huggingface-hub==0.11.1\n!pip install tqdm==4.64.1\n!pip install  pytorch==1.13.1\n!pip install torchvision==0.14.1","metadata":{"_uuid":"088a93b3-4c76-4ba8-97d0-195e9f239fe3","_cell_guid":"5eb39bb4-9948-4c50-a401-8798bc0b5d05","collapsed":false,"jupyter":{"outputs_hidden":false},"execution":{"iopub.status.busy":"2024-05-02T05:37:28.741993Z","iopub.execute_input":"2024-05-02T05:37:28.742580Z","iopub.status.idle":"2024-05-02T05:39:19.669936Z","shell.execute_reply.started":"2024-05-02T05:37:28.742550Z","shell.execute_reply":"2024-05-02T05:39:19.668685Z"},"trusted":true},"execution_count":4,"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: wandb==0.13.9 in /opt/conda/lib/python3.10/site-packages (0.13.9)\nRequirement already satisfied: Click!=8.0.0,>=7.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (8.1.7)\nRequirement already satisfied: GitPython>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (3.1.41)\nRequirement already satisfied: requests<3,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (2.31.0)\nRequirement already satisfied: psutil>=5.0.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (5.9.3)\nRequirement already satisfied: sentry-sdk>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (1.45.0)\nRequirement already satisfied: docker-pycreds>=0.4.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (0.4.0)\nRequirement already satisfied: PyYAML in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (6.0.1)\nRequirement already satisfied: pathtools in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (0.1.2)\nRequirement already satisfied: setproctitle in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (1.3.3)\nRequirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (69.0.3)\nRequirement already satisfied: appdirs>=1.4.3 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (1.4.4)\nRequirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /opt/conda/lib/python3.10/site-packages (from wandb==0.13.9) (3.20.3)\nRequirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from docker-pycreds>=0.4.0->wandb==0.13.9) (1.16.0)\nRequirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.10/site-packages (from GitPython>=1.0.0->wandb==0.13.9) (4.0.11)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.13.9) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.13.9) (3.6)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.13.9) (1.26.18)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.13.9) (2024.2.2)\nRequirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb==0.13.9) (5.0.1)\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: scipy==1.10.0 in /opt/conda/lib/python3.10/site-packages (1.10.0)\nRequirement already satisfied: numpy<1.27.0,>=1.19.5 in /opt/conda/lib/python3.10/site-packages (from scipy==1.10.0) (1.26.4)\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mCollecting torchaudio==0.13.1\n  Using cached torchaudio-0.13.1-cp310-cp310-manylinux1_x86_64.whl.metadata (1.2 kB)\nCollecting torch==1.13.1 (from torchaudio==0.13.1)\n  Using cached torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl.metadata (24 kB)\nRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchaudio==0.13.1) (4.9.0)\nRequirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchaudio==0.13.1) (11.7.99)\nRequirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchaudio==0.13.1) (8.5.0.96)\nRequirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchaudio==0.13.1) (11.10.3.66)\nRequirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchaudio==0.13.1) (11.7.99)\nRequirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->torchaudio==0.13.1) (69.0.3)\nRequirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->torchaudio==0.13.1) (0.42.0)\nUsing cached torchaudio-0.13.1-cp310-cp310-manylinux1_x86_64.whl (4.2 MB)\nUsing cached torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mInstalling collected packages: torch, torchaudio\n  Attempting uninstall: torchaudio\n    Found existing installation: torchaudio 2.1.2\n    Uninstalling torchaudio-2.1.2:\n      Successfully uninstalled torchaudio-2.1.2\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\ntorchdata 0.7.1 requires torch>=2, but you have torch 1.13.1 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed torch-1.13.1 torchaudio-0.13.1\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mCollecting huggingface-hub==0.11.1\n  Using cached huggingface_hub-0.11.1-py3-none-any.whl.metadata (7.5 kB)\nRequirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (3.13.1)\nRequirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (2.31.0)\nRequirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (4.64.1)\nRequirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (6.0.1)\nRequirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (4.9.0)\nRequirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub==0.11.1) (21.3)\nRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.9->huggingface-hub==0.11.1) (3.1.1)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub==0.11.1) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub==0.11.1) (3.6)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub==0.11.1) (1.26.18)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub==0.11.1) (2024.2.2)\nUsing cached huggingface_hub-0.11.1-py3-none-any.whl (182 kB)\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mInstalling collected packages: huggingface-hub\n  Attempting uninstall: huggingface-hub\n    Found existing installation: huggingface-hub 0.22.2\n    Uninstalling huggingface-hub-0.22.2:\n      Successfully uninstalled huggingface-hub-0.22.2\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\ndatasets 2.18.0 requires huggingface-hub>=0.19.4, but you have huggingface-hub 0.11.1 which is incompatible.\ntokenizers 0.15.2 requires huggingface_hub<1.0,>=0.16.4, but you have huggingface-hub 0.11.1 which is incompatible.\ntransformers 4.39.3 requires huggingface-hub<1.0,>=0.19.3, but you have huggingface-hub 0.11.1 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed huggingface-hub-0.11.1\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: tqdm==4.64.1 in /opt/conda/lib/python3.10/site-packages (4.64.1)\n\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement pytorch==1.13.1 (from versions: 0.1.2, 1.0.2)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for pytorch==1.13.1\u001b[0m\u001b[31m\n\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mCollecting torchvision==0.14.1\n  Downloading torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl.metadata (11 kB)\nRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torchvision==0.14.1) (4.9.0)\nRequirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from torchvision==0.14.1) (1.26.4)\nRequirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from torchvision==0.14.1) (2.31.0)\nRequirement already satisfied: torch==1.13.1 in /opt/conda/lib/python3.10/site-packages (from torchvision==0.14.1) (1.13.1)\nRequirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.10/site-packages (from torchvision==0.14.1) (9.5.0)\nRequirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchvision==0.14.1) (11.7.99)\nRequirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchvision==0.14.1) (8.5.0.96)\nRequirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchvision==0.14.1) (11.10.3.66)\nRequirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch==1.13.1->torchvision==0.14.1) (11.7.99)\nRequirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->torchvision==0.14.1) (69.0.3)\nRequirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->torchvision==0.14.1) (0.42.0)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision==0.14.1) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision==0.14.1) (3.6)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision==0.14.1) (1.26.18)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision==0.14.1) (2024.2.2)\nDownloading torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl (24.2 MB)\n\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m24.2/24.2 MB\u001b[0m \u001b[31m45.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0mm\n\u001b[?25h\u001b[33mWARNING: Ignoring invalid distribution -orch (/opt/conda/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n\u001b[0mInstalling collected packages: torchvision\n  Attempting uninstall: torchvision\n    Found existing installation: torchvision 0.16.2\n    Uninstalling torchvision-0.16.2:\n      Successfully uninstalled torchvision-0.16.2\nSuccessfully installed torchvision-0.14.1\n","output_type":"stream"}]},{"cell_type":"code","source":"cd /root/","metadata":{"execution":{"iopub.status.busy":"2024-05-02T05:40:24.891869Z","iopub.execute_input":"2024-05-02T05:40:24.892569Z","iopub.status.idle":"2024-05-02T05:40:24.898997Z","shell.execute_reply.started":"2024-05-02T05:40:24.892532Z","shell.execute_reply":"2024-05-02T05:40:24.898033Z"},"trusted":true},"execution_count":5,"outputs":[{"name":"stdout","text":"/root\n","output_type":"stream"}]},{"cell_type":"code","source":"!cp -r /kaggle/input/nyu-depth-v2/nyu_data/data/nyu2_test /root/","metadata":{"execution":{"iopub.status.busy":"2024-05-02T05:41:05.654763Z","iopub.execute_input":"2024-05-02T05:41:05.655169Z","iopub.status.idle":"2024-05-02T05:41:25.031019Z","shell.execute_reply.started":"2024-05-02T05:41:05.655138Z","shell.execute_reply":"2024-05-02T05:41:25.029640Z"},"trusted":true},"execution_count":7,"outputs":[]},{"cell_type":"code","source":"!cp -r /kaggle/input/synczip/sync /root/","metadata":{"execution":{"iopub.status.busy":"2024-05-02T05:49:28.021354Z","iopub.execute_input":"2024-05-02T05:49:28.022201Z","iopub.status.idle":"2024-05-02T05:55:08.735191Z","shell.execute_reply.started":"2024-05-02T05:49:28.022167Z","shell.execute_reply":"2024-05-02T05:55:08.733838Z"},"trusted":true},"execution_count":29,"outputs":[]},{"cell_type":"code","source":"import os\npath = '/kaggle/working/ZoeDepth/zoedepth/utils/config.py'\nif os.path.isfile(path):\n    os.remove(path)\n","metadata":{"execution":{"iopub.status.busy":"2024-05-02T06:01:42.380252Z","iopub.execute_input":"2024-05-02T06:01:42.380734Z","iopub.status.idle":"2024-05-02T06:01:42.386853Z","shell.execute_reply.started":"2024-05-02T06:01:42.380678Z","shell.execute_reply":"2024-05-02T06:01:42.385781Z"},"trusted":true},"execution_count":35,"outputs":[]},{"cell_type":"code","source":"import os\npath = '/kaggle/working/ZoeDepth/zoedepth/models/zoedepth/config_zoedepth.json'\nif os.path.isfile(path):\n    os.remove(path)\n","metadata":{"execution":{"iopub.status.busy":"2024-05-02T06:07:08.716920Z","iopub.execute_input":"2024-05-02T06:07:08.717798Z","iopub.status.idle":"2024-05-02T06:07:08.723324Z","shell.execute_reply.started":"2024-05-02T06:07:08.717757Z","shell.execute_reply":"2024-05-02T06:07:08.722147Z"},"trusted":true},"execution_count":38,"outputs":[]},{"cell_type":"code","source":"!cp -r /kaggle/input/confic/config_zoedepth.json /kaggle/working/ZoeDepth/zoedepth/models/zoedepth","metadata":{"execution":{"iopub.status.busy":"2024-05-02T06:08:46.429802Z","iopub.execute_input":"2024-05-02T06:08:46.430711Z","iopub.status.idle":"2024-05-02T06:08:47.430762Z","shell.execute_reply.started":"2024-05-02T06:08:46.430675Z","shell.execute_reply":"2024-05-02T06:08:47.429523Z"},"trusted":true},"execution_count":39,"outputs":[]},{"cell_type":"code","source":"!cp /kaggle/input/confic1/config.py /kaggle/working/ZoeDepth/zoedepth/utils","metadata":{"execution":{"iopub.status.busy":"2024-05-02T06:01:47.299472Z","iopub.execute_input":"2024-05-02T06:01:47.299880Z","iopub.status.idle":"2024-05-02T06:01:48.265926Z","shell.execute_reply.started":"2024-05-02T06:01:47.299849Z","shell.execute_reply":"2024-05-02T06:01:48.264549Z"},"trusted":true},"execution_count":36,"outputs":[]},{"cell_type":"code","source":"!cp -r /kaggle/input/synczip/sync","metadata":{"execution":{"iopub.status.busy":"2024-05-02T05:47:29.695405Z","iopub.execute_input":"2024-05-02T05:47:29.696144Z","iopub.status.idle":"2024-05-02T05:47:30.653280Z","shell.execute_reply.started":"2024-05-02T05:47:29.696110Z","shell.execute_reply":"2024-05-02T05:47:30.652311Z"},"trusted":true},"execution_count":19,"outputs":[{"name":"stdout","text":"cp: missing destination file operand after '/kaggle/input/synczip/sync'\nTry 'cp --help' for more information.\n","output_type":"stream"}]},{"cell_type":"code","source":"!wandb login d862f89f04220cc74b5d86ad3add94ca5102ddc6\n!python /kaggle/working/ZoeDepth/train_mono.py -m zoedepth --pretrained_resource=\"\"","metadata":{"_uuid":"2d22cbad-128b-43cf-b144-f91143cad179","_cell_guid":"9d96ae76-ac54-4889-886b-070a21193155","collapsed":false,"jupyter":{"outputs_hidden":false},"execution":{"iopub.status.busy":"2024-05-02T06:08:50.462376Z","iopub.execute_input":"2024-05-02T06:08:50.463043Z","iopub.status.idle":"2024-05-02T07:10:57.912404Z","shell.execute_reply.started":"2024-05-02T06:08:50.463008Z","shell.execute_reply":"2024-05-02T07:10:57.910934Z"},"trusted":true},"execution_count":40,"outputs":[{"name":"stdout","text":"\u001b[34m\u001b[1mwandb\u001b[0m: Appending key for api.wandb.ai to your netrc file: /root/.netrc\n0\ntcp://127.0.0.1:15009\nConfig:\n{'attractor_alpha': 1000,\n 'attractor_gamma': 2,\n 'attractor_kind': 'mean',\n 'attractor_type': 'inv',\n 'aug': True,\n 'avoid_boundary': False,\n 'batch_size': 2,\n 'bin_centers_type': 'softplus',\n 'bin_embedding_dim': 128,\n 'bs': 2,\n 'clip_grad': 0.1,\n 'cycle_momentum': True,\n 'data_path': '/root/./sync',\n 'data_path_eval': '/root/./nyu2_test',\n 'dataset': 'nyu',\n 'degree': 1.0,\n 'dist_backend': 'nccl',\n 'dist_url': 'tcp://127.0.0.1:15009',\n 'distributed': True,\n 'div_factor': 1,\n 'do_kb_crop': False,\n 'do_random_rotate': True,\n 'eigen_crop': True,\n 'encoder_lr_factor': 10,\n 'epochs': 5,\n 'filenames_file': '/kaggle/working/ZoeDepth/train_test_inputs/nyudepthv2_train_files_with_gt.txt',\n 'filenames_file_eval': '/kaggle/working/ZoeDepth/train_test_inputs/nyudepthv2_test_files_with_gt.txt',\n 'final_div_factor': 10000,\n 'freeze_midas_bn': True,\n 'garg_crop': False,\n 'gpu': None,\n 'gt_path': '/root/./sync',\n 'gt_path_eval': '/root/./nyu2_test',\n 'img_size': [384, 512],\n 'input_height': 480,\n 'input_width': 640,\n 'inverse_midas': False,\n 'log_images_every': 0.1,\n 'lr': 0.000161,\n 'max_depth': 10,\n 'max_depth_diff': 10,\n 'max_depth_eval': 10,\n 'max_temp': 50.0,\n 'max_translation': 100,\n 'memory_efficient': True,\n 'midas_lr_factor': 1,\n 'midas_model_type': 'DPT_BEiT_L_384',\n 'min_depth': 0.001,\n 'min_depth_diff': -10,\n 'min_depth_eval': 0.001,\n 'min_temp': 0.0212,\n 'mode': 'train',\n 'model': 'zoedepth',\n 'n_attractors': [16, 8, 4, 1],\n 'n_bins': 64,\n 'name': 'ZoeDepth',\n 'ngpus_per_node': 1,\n 'notes': '',\n 'num_workers': 16,\n 'output_distribution': 'logbinomial',\n 'pct_start': 0.7,\n 'pos_enc_lr_factor': 10,\n 'prefetch': False,\n 'pretrained_resource': '',\n 'print_losses': False,\n 'project': 'MonoDepth3-nyu',\n 'random_crop': False,\n 'random_translate': False,\n 'rank': 0,\n 'root': '.',\n 'same_lr': False,\n 'save_dir': '/root/shortcuts/monodepth3_checkpoints',\n 'shared_dict': None,\n 'tags': '',\n 'three_phase': False,\n 'train_midas': True,\n 'trainer': 'zoedepth',\n 'translate_prob': 0.2,\n 'uid': None,\n 'use_amp': False,\n 'use_pretrained_midas': True,\n 'use_shared_dict': False,\n 'validate_every': 0.25,\n 'version_name': 'v1',\n 'w_domain': 0.2,\n 'w_grad': 0,\n 'w_reg': 0,\n 'w_si': 1,\n 'wd': 0.01,\n 'workers': 16,\n 'world_size': 1}\nimg_size [384, 512]\nUsing cache found in /root/.cache/torch/hub/intel-isl_MiDaS_master\n/opt/conda/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)\n  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]\nParams passed to Resize transform:\n\twidth:  512\n\theight:  384\n\tresize_target:  True\n\tkeep_aspect_ratio:  False\n\tensure_multiple_of:  32\n\tresize_method:  minimal\nDevice 0 Rank 0 batch size 2 Workers 16\nTotal parameters : 344.82M\n/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.\n  warnings.warn(_create_warning_msg(\nUsing diff LR\nTraining ZoeDepth\n\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mbuitiendungt5nhvt\u001b[0m. Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n\u001b[34m\u001b[1mwandb\u001b[0m: wandb version 0.16.6 is available!  To upgrade, please run:\n\u001b[34m\u001b[1mwandb\u001b[0m:  $ pip install wandb --upgrade\n\u001b[34m\u001b[1mwandb\u001b[0m: Tracking run with wandb version 0.13.9\n\u001b[34m\u001b[1mwandb\u001b[0m: Run data is saved locally in \u001b[35m\u001b[1m./wandb/run-20240502_060911-54vk7f9e\u001b[0m\n\u001b[34m\u001b[1mwandb\u001b[0m: Run \u001b[1m`wandb offline`\u001b[0m to turn off syncing.\n\u001b[34m\u001b[1mwandb\u001b[0m: Syncing run \u001b[33mZoeDepthv1_02-May_06-09-78c8332cfec2\u001b[0m\n\u001b[34m\u001b[1mwandb\u001b[0m: ⭐️ View project at \u001b[34m\u001b[4mhttps://wandb.ai/buitiendungt5nhvt/MonoDepth3-nyu\u001b[0m\n\u001b[34m\u001b[1mwandb\u001b[0m: 🚀 View run at \u001b[34m\u001b[4mhttps://wandb.ai/buitiendungt5nhvt/MonoDepth3-nyu/runs/54vk7f9e\u001b[0m\n/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.\n  warnings.warn(_create_warning_msg(\nEpoch: 1/5. Loop: Train:   0%|                        | 0/12116 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.\ngrad.sizes() = [1, 128, 1, 1], strides() = [128, 1, 128, 128]\nbucket_view.sizes() = [1, 128, 1, 1], strides() = [128, 1, 1, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)\n  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\nEpoch: 1/5. Loop: Train:  25%|██▏      | 3028/12116 [1:00:32<2:59:33,  1.19s/it]\nEpoch: 1/5. Loop: Validation:   0%|                     | 0/654 [00:01<?, ?it/s]\u001b[A\nEpoch: 1/5. Loop: Train:  25%|██▏      | 3028/12116 [1:00:37<3:01:58,  1.20s/it]\n\u001b[34m\u001b[1mwandb\u001b[0m: Waiting for W&B process to finish... \u001b[32m(success).\u001b[0m\n\u001b[34m\u001b[1mwandb\u001b[0m: | 1.276 MB of 1.328 MB uploaded (0.000 MB deduped)\n\u001b[34m\u001b[1mwandb\u001b[0m: Run history:\n\u001b[34m\u001b[1mwandb\u001b[0m:       Epoch ▁\n\u001b[34m\u001b[1mwandb\u001b[0m: Train/SILog █▂▁▁▂▁▁▂▁▁▂▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁\n\u001b[34m\u001b[1mwandb\u001b[0m: \n\u001b[34m\u001b[1mwandb\u001b[0m: Run summary:\n\u001b[34m\u001b[1mwandb\u001b[0m:       Epoch 0\n\u001b[34m\u001b[1mwandb\u001b[0m: Train/SILog 0.72578\n\u001b[34m\u001b[1mwandb\u001b[0m: \n\u001b[34m\u001b[1mwandb\u001b[0m: 🚀 View run \u001b[33mZoeDepthv1_02-May_06-09-78c8332cfec2\u001b[0m at: \u001b[34m\u001b[4mhttps://wandb.ai/buitiendungt5nhvt/MonoDepth3-nyu/runs/54vk7f9e\u001b[0m\n\u001b[34m\u001b[1mwandb\u001b[0m: Synced 6 W&B file(s), 9 media file(s), 0 artifact file(s) and 0 other file(s)\n\u001b[34m\u001b[1mwandb\u001b[0m: Find logs at: \u001b[35m\u001b[1m./wandb/run-20240502_060911-54vk7f9e/logs\u001b[0m\nTraceback (most recent call last):\n  File \"/kaggle/working/ZoeDepth/train_mono.py\", line 169, in <module>\n    mp.spawn(main_worker, nprocs=ngpus_per_node,\n  File \"/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py\", line 240, in spawn\n    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')\n  File \"/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py\", line 198, in start_processes\n    while not context.join():\n  File \"/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py\", line 160, in join\n    raise ProcessRaisedException(msg, error_index, failed_process.pid)\ntorch.multiprocessing.spawn.ProcessRaisedException: \n\n-- Process 0 terminated with the following error:\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py\", line 69, in _wrap\n    fn(i, *args)\n  File \"/kaggle/working/ZoeDepth/train_mono.py\", line 104, in main_worker\n    trainer.train()\n  File \"/kaggle/working/ZoeDepth/zoedepth/trainers/base_trainer.py\", line 214, in train\n    metrics, test_losses = self.validate()\n  File \"/kaggle/working/ZoeDepth/zoedepth/trainers/base_trainer.py\", line 263, in validate\n    for i, batch in tqdm(enumerate(self.test_loader), desc=f\"Epoch: {self.epoch + 1}/{self.config.epochs}. Loop: Validation\", total=len(self.test_loader), disable=not is_rank_zero(self.config)):\n  File \"/opt/conda/lib/python3.10/site-packages/tqdm/std.py\", line 1195, in __iter__\n    for obj in iterable:\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py\", line 628, in __next__\n    data = self._next_data()\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py\", line 1333, in _next_data\n    return self._process_data(data)\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py\", line 1359, in _process_data\n    data.reraise()\n  File \"/opt/conda/lib/python3.10/site-packages/torch/_utils.py\", line 543, in reraise\n    raise exception\nFileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py\", line 302, in _worker_loop\n    data = fetcher.fetch(index)\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 58, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 58, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/kaggle/working/ZoeDepth/zoedepth/data/data_mono.py\", line 380, in __getitem__\n    image = np.asarray(self.reader.open(image_path),\n  File \"/kaggle/working/ZoeDepth/zoedepth/data/data_mono.py\", line 267, in open\n    return Image.open(fpath)\n  File \"/opt/conda/lib/python3.10/site-packages/PIL/Image.py\", line 3236, in open\n    fp = builtins.open(filename, \"rb\")\nFileNotFoundError: [Errno 2] No such file or directory: '/root/./nyu2_test/bathroom/rgb_00045.jpg'\n\n\n","output_type":"stream"}]}]}